# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0ca4c3d2247f756a2ad957b876976173"
name = "polaris-viz-sample"
handle = "polaris-viz-sample"
application_url = "https://guards-bi-mx-somehow.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "stock-impact-dev.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://guards-bi-mx-somehow.trycloudflare.com/auth/callback",
  "https://guards-bi-mx-somehow.trycloudflare.com/auth/shopify/callback",
  "https://guards-bi-mx-somehow.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
